# Stage 1: Build React App 
FROM node:18 as build

WORKDIR /app
VOLUME /app
# Copy package.json and package-lock.json first to leverage Docker cache        
COPY ./client/package*.json ./
RUN npm install
COPY ./client/ ./
RUN npm run build

# Stage 2: Serve using Nginx
FROM nginx:alpine

# Optional: custom Nginx config
#COPY ../nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy built app to Nginx html directory
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
